from enum import IntEnum

class Game(IntEnum):
    ALL                                     = 281474976710655
    NONE                                    = 0
    ADVENTURE                               = 2 **   0
    BLASPHEMOUS                             = 2 **   1
    BUMPER_STICKERS                         = 2 **   2
    CHECKSFINDER                            = 2 **   3
    CLIQUE                                  = 2 **   4
    DARK_SOULS_III                          = 2 **   5
    DLCQUEST                                = 2 **   6
    DONKEY_KONG_COUNTRY_3                   = 2 **   7
    DOOM_1993                               = 2 **   8
    FACTORIO                                = 2 **   9
    FINAL_FANTASY                           = 2 **  10
    HOLLOW_KNIGHT                           = 2 **  11
    HYLICS_2                                = 2 **  12
    KINGDOM_HEARTS_2                        = 2 **  13
    THE_LEGEND_OF_ZELDA                     = 2 **  14
    A_LINK_TO_THE_PAST                      = 2 **  15
    LINKS_AWAKENING_DX                      = 2 **  16
    LUFIA_II_ANCIENT_CAVE                   = 2 **  17
    MEGAMAN_BATTLE_NETWORK_3                = 2 **  18
    MERITOUS                                = 2 **  19
    THE_MESSENGER                           = 2 **  20
    MINECRAFT                               = 2 **  21
    MUSE_DASH                               = 2 **  22
    NOITA                                   = 2 **  23
    OCARINA_OF_TIME                         = 2 **  24
    OVERCOOKED_2                            = 2 **  25
    POKEMON_RED_AND_BLUE                    = 2 **  26
    RAFT                                    = 2 **  27
    RISK_OF_RAIN_2                          = 2 **  28
    ROGUE_LEGACY                            = 2 **  29
    SECRET_OF_EVERMORE                      = 2 **  30
    SLAY_THE_SPIRE                          = 2 **  31
    SMZ3                                    = 2 **  32
    SONIC_ADVENTURE_2_BATTLE                = 2 **  33
    STARCRAFT_2_WINGS_OF_LIBERTY            = 2 **  34
    STARDEW_VALLEY                          = 2 **  35
    SUBNAUTICA                              = 2 **  36
    SUDOKU                                  = 2 **  37
    SUPER_MARIO_64                          = 2 **  38
    SUPER_MARIO_WORLD                       = 2 **  39
    SUPER_METROID                           = 2 **  40
    TERRARIA                                = 2 **  41
    TIMESPINER                              = 2 **  42
    UNDERTALE                               = 2 **  43
    VVVVVV                                  = 2 **  44
    WARGROOVE                               = 2 **  45
    THE_WITNESS                             = 2 **  46
    ZILLION                                 = 2 **  47